# Generated by Django 2.1.3 on 2018-11-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_shower', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aggregate_shower_savings',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='average_shower_time',
            field=models.FloatField(default=0),
        ),
    ]
