# Generated by Django 2.1.3 on 2018-11-04 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wifi_shower', '0002_auto_20181105_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preheat_cycle', models.FloatField(blank=True, null=True)),
                ('shower_cycle', models.FloatField(blank=True, null=True)),
                ('shower_temp', models.FloatField(blank=True, null=True)),
                ('old_shower_habits', models.FloatField(blank=True, null=True)),
                ('water_used', models.FloatField(blank=True, null=True)),
                ('water_saved', models.FloatField(blank=True, null=True)),
                ('challenge_level', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_shower_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
