# Generated by Django 2.1.3 on 2018-11-04 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wifi_shower', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoweringData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('shower_mode', models.IntegerField(default=0)),
                ('preheat_cycle', models.FloatField(blank=True, null=True)),
                ('shower_cycle', models.FloatField(blank=True, null=True)),
                ('old_shower_habits', models.FloatField(blank=True, null=True)),
                ('water_used', models.FloatField(blank=True, null=True)),
                ('water_saved', models.FloatField(blank=True, null=True)),
                ('shower_temp', models.FloatField(blank=True, null=True)),
                ('mixing_temp', models.FloatField(blank=True, null=True)),
                ('challenge_level', models.FloatField(blank=True, null=True)),
                ('aggregate_water_used', models.FloatField(blank=True, null=True)),
                ('average_water_used', models.FloatField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wifi_shower.Device')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wifi_shower.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'showering_data',
            },
        ),
    ]
